### ISSUE TITLE
Does not handle dynamic "String" route parameter value

### ISSUE THREAD

**Issue by marc-medley** [pointfreeco/swift-html-vapor#3]
`swift-html-vapor` does not accept a runtime `String` value.  More specifically, `swift-html-vapor` does not compile when a `String` parameter is added to a Vapor route for use within a `Html.Node` _"string"_.

**Steps To Reproduce**

Set up Vapor route to accept a String parameter

``` swift
// url route "localhost:8080/some-string-value"
router.get(String.parameter) {
    (request: Request) -> Html.Node in
    let  someStringValue: String = try request.parameters.next(String.self)
    //print("someStringValue = \(someStringValue)")
    let node: Html.Node = html([
        head([style(stylesheet)]),
        
        body([
            h1(["swift-html-vapor with \(someStringValue)"]),
                // … more unchanged code here
            ]) // end body
        ]) // end html
    return node
}
```

**Expected Result**

Expected to compile, run, and work with any valid "localhost:8080/some-string-value" URL.

**Actual Result**

![SwiftHtmlBugHighlighted](https://user-images.githubusercontent.com/15098151/54854564-963c4c80-4cb0-11e9-84d0-a4de0e44f693.png)

>.../swift-html-vapor-master/Sources/HtmlVaporSupportExample/main.swift:52:24: '[Any]' is not convertible to '[Node]'

**Comment by stephencelis** [comment]
Hi @marc-medley! That error is pretty tough to decipher, but the main issue is that `Node` doesn't conform to `ExpressibleByStringInterpolation`. We should fix this for Swift 5, but in order to make a `text` node you can use the `.text` case:

``` swift
h1([.text("swift-html-vapor with \(someStringValue)")])
```

**Comment by mbrandonw** [comment]
@marc-medley we just released [0.3.0](https://github.com/pointfreeco/swift-html/releases/tag/0.3.0) of Html, which includes Swift 5 support and string interpolations. let us know if you have any questions...

**Comment by stephencelis** [comment]
Fixed with the release! https://github.com/pointfreeco/swift-html-vapor/releases/tag/0.3.0

**Comment by marc-medley** [comment]
@stephencelis [belate] Thank You!  for your timely replay regarding.  

With the `Node.text` info I was about to get a basic Vapor async Service running with `swift-html`.  The project is located at https://github.com/VaporExamplesLab/eval-vapor-leaf-stencil. 

However, I could help with the Swift 5 testing since I'm still on High Sierra/Swift 4. [See https://github.com/pointfreeco/swift-html/issues/53]
